/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpassignment;


import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
/**
 *
 * @author devil
 */
public class Booking extends javax.swing.JFrame {
 
    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
       
        
    }
    
    private boolean isInteger(String check){
        try
    {
        Integer.parseInt(check);
        return true;
    } catch (NumberFormatException ex)
    {
        return false;
    }
}

   private static boolean isValid(String email) {
      String regex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
      return email.matches(regex);
   }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbName6 = new javax.swing.JLabel();
        btnBook_BK = new javax.swing.JButton();
        btnback_BK = new javax.swing.JButton();
        lbName7 = new javax.swing.JLabel();
        txtName_BK = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        txtEmail_BK = new javax.swing.JTextField();
        lbName1 = new javax.swing.JLabel();
        txtIC_BK = new javax.swing.JTextField();
        lbName2 = new javax.swing.JLabel();
        txtNumber_BK = new javax.swing.JTextField();
        lbName4 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbName5 = new javax.swing.JLabel();
        dcStart_BK = new com.toedter.calendar.JDateChooser();
        dcEnd_BK = new com.toedter.calendar.JDateChooser();
        btnpickroom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setText("Booking For Customer");

        lbName6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lbName6.setForeground(new java.awt.Color(55, 55, 55));
        lbName6.setText("From");

        btnBook_BK.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnBook_BK.setText("Next");
        btnBook_BK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBook_BKActionPerformed(evt);
            }
        });

        btnback_BK.setText("Back");
        btnback_BK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback_BKActionPerformed(evt);
            }
        });

        lbName7.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lbName7.setForeground(new java.awt.Color(55, 55, 55));
        lbName7.setText("To");

        txtName_BK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName_BKActionPerformed(evt);
            }
        });

        lbEmail.setText("Email");

        txtEmail_BK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail_BKActionPerformed(evt);
            }
        });

        lbName1.setText("IC/Passport");

        txtIC_BK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIC_BKActionPerformed(evt);
            }
        });

        lbName2.setText("Contact Number");

        txtNumber_BK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumber_BKActionPerformed(evt);
            }
        });

        lbName4.setText("Days of stays:");

        lbName.setText("Name");

        lbName5.setBackground(new java.awt.Color(192, 192, 192));
        lbName5.setText("Booking date");

        dcStart_BK.setMinSelectableDate(new java.util.Date(-62135794692000L));

        dcEnd_BK.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                dcEnd_BKComponentAdded(evt);
            }
        });
        dcEnd_BK.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dcEnd_BKAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        dcEnd_BK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dcEnd_BKFocusLost(evt);
            }
        });
        dcEnd_BK.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                dcEnd_BKComponentShown(evt);
            }
        });

        btnpickroom.setText("Pick room");
        btnpickroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpickroomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnback_BK, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(145, 145, 145))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbName)
                                    .addComponent(txtName_BK, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail_BK, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEmail)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbName4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnpickroom))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbName1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIC_BK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbName2)
                                    .addComponent(txtNumber_BK, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbName5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnBook_BK, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcStart_BK, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbName6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbName7)
                    .addComponent(dcEnd_BK, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbName)
                    .addComponent(lbEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbName2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumber_BK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName_BK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail_BK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIC_BK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(lbName5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName6, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbName7))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcStart_BK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcEnd_BK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpickroom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnBook_BK, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnback_BK)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBook_BKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBook_BKActionPerformed
  SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
      Date Start = dcStart_BK.getDate();
      Date End = dcEnd_BK.getDate();
      String name = txtName_BK.getText().toString();
      String email = txtEmail_BK.getText().toString();
      String ic = txtIC_BK.getText().toString();
      String number = txtNumber_BK.getText().toString();
      String roomname = btnpickroom.getText().toString();
      
      if (name.trim().isEmpty() || email.trim().isEmpty() || ic.trim().isEmpty() || number.trim().isEmpty() || Start == null || End == null || roomname == "Pick room"){
          JOptionPane.showMessageDialog(null,"There is empty details.");
      }
      else if(isInteger(ic) == false || isInteger(number) == false){
      JOptionPane.showMessageDialog(null,"Please make sure your IC/Passport and Contact Number is appropriate.");     
      }      
      else if (this.isValid(email) == false){
       JOptionPane.showMessageDialog(null,"Please make sure your Email is appropriate.");   
      }
      else{
        String firstdate = sdf.format(Start);
        String seconddate = sdf.format(End);
        LocalDate date1 = LocalDate.parse(firstdate);
	LocalDate date2 = LocalDate.parse(seconddate);
        LocalDate today = LocalDate.now();
        
  long diffindays = ChronoUnit.DAYS.between(date1, date2);
  long passcheck =  ChronoUnit.DAYS.between(today, date1);

  
  if (diffindays < 0 || passcheck < 0){
      JOptionPane.showMessageDialog(null,"Please select a valid date."); 
  }
  
  else {
      new payment(this,Start,End, name, email, ic, number, roomname).setVisible(true);
  }     
      }
    }//GEN-LAST:event_btnBook_BKActionPerformed

    private void txtName_BKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName_BKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName_BKActionPerformed

    private void txtEmail_BKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail_BKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail_BKActionPerformed

    private void txtIC_BKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIC_BKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIC_BKActionPerformed

    private void txtNumber_BKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumber_BKActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_txtNumber_BKActionPerformed

    private void dcEnd_BKComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_dcEnd_BKComponentAdded

    }//GEN-LAST:event_dcEnd_BKComponentAdded

    private void dcEnd_BKAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dcEnd_BKAncestorAdded

    }//GEN-LAST:event_dcEnd_BKAncestorAdded

    private void dcEnd_BKFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcEnd_BKFocusLost

    }//GEN-LAST:event_dcEnd_BKFocusLost

    private void dcEnd_BKComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dcEnd_BKComponentShown

    }//GEN-LAST:event_dcEnd_BKComponentShown

    private void btnpickroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpickroomActionPerformed
        Date Start = dcStart_BK.getDate();
        Date End = dcEnd_BK.getDate();
        if (Start != null && End != null){
        new pick_room(this,Start,End).setVisible(true);}
        else{
            JOptionPane.showMessageDialog(null,"Please select a proper date before selecting rooms.");
        }
    }//GEN-LAST:event_btnpickroomActionPerformed

    private void btnback_BKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback_BKActionPerformed
    new StaffMain().setVisible(true);
    this.dispose();
               // TODO add your handling code here:
    }//GEN-LAST:event_btnback_BKActionPerformed

    public void changeButtonText(String r){
        this.btnpickroom.setText(r);
    }
    

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook_BK;
    private javax.swing.JButton btnback_BK;
    private javax.swing.JButton btnpickroom;
    private com.toedter.calendar.JDateChooser dcEnd_BK;
    private com.toedter.calendar.JDateChooser dcStart_BK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbName1;
    private javax.swing.JLabel lbName2;
    private javax.swing.JLabel lbName4;
    private javax.swing.JLabel lbName5;
    private javax.swing.JLabel lbName6;
    private javax.swing.JLabel lbName7;
    private javax.swing.JTextField txtEmail_BK;
    private javax.swing.JTextField txtIC_BK;
    private javax.swing.JTextField txtName_BK;
    private javax.swing.JTextField txtNumber_BK;
    // End of variables declaration//GEN-END:variables
}
