/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpassignment;

import java.awt.event.KeyEvent;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author devil
 */
public class payment extends javax.swing.JFrame {

    private Booking booking;
    private Date startD,endD;
    private String name,email,icnum,number,roomname;
    private BigDecimal pay,roomcharges,servicetax,tourismtax,totalfees;
    
    private int bookingID;
  
   
    public payment(Booking b,Date sd, Date ed, String n, String em, String ic, String num, String roomN) {
        initComponents();
        this.booking = b;
        startD = sd;
        endD = ed;
        name = n;
        email = em;
        icnum = ic;
        number = num;
        roomname = roomN;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String first = sdf.format(startD);
        String second = sdf.format(endD);
        LocalDate startDate = LocalDate.parse(first);
        LocalDate endDate = LocalDate.parse(second);

        
   long stayofday = ChronoUnit.DAYS.between(startDate, endDate);
   String D_O_S = Long.toString(stayofday);
   Dos.setText(D_O_S +" days");
   
   BigDecimal days = new BigDecimal(stayofday);
   BigDecimal roomfeespernight = new BigDecimal(350);
   BigDecimal servicetaxfees = new BigDecimal(0.1);
   BigDecimal tourismtaxfees = new BigDecimal(10);
   
   roomcharges = days.multiply(roomfeespernight);
   servicetax  = roomcharges.multiply(servicetaxfees);
   servicetax = servicetax.setScale(2, BigDecimal.ROUND_HALF_EVEN);
   tourismtax  = days.multiply(tourismtaxfees);
   totalfees =  roomcharges.add(servicetax).add(tourismtax);
   
   
   lbRoomCharges.setText("RM" + roomcharges);
   lbServiceTax.setText("RM" + servicetax);
   lbTourismTax.setText("RM" + tourismtax);
   lbTotal.setText("RM" + totalfees);
   
   
   
   txtchange.setEditable(false);
   
           File file = new File("booking.txt");
        String bkid;
        List<String> bklist = new ArrayList<>();
        try{
            
            Scanner inputFile = new Scanner(file);

            while (inputFile.hasNext()){
                bkid = inputFile.nextLine();
                if (bkid !=null)bklist.add(bkid);
                inputFile.nextLine();
                inputFile.nextLine();
                inputFile.nextLine();
                inputFile.nextLine();
                inputFile.nextLine();
                inputFile.nextLine();
                inputFile.nextLine();            

                inputFile.nextLine();
            }
            inputFile.close();
        }
        catch (FileNotFoundException ex){
            System.out.println("Unable to open file due to "+ex);
                
            }
        
        if (bklist.size() != 0){
        int size = bklist.size();
        String get_id_index;
        int nextbkid;
        int is_latest = 0;
        for (int i=0; i < size; i++){
            get_id_index = bklist.get(i);
            nextbkid = Integer.parseInt(get_id_index);
            
            if(i == 0){
            get_id_index = bklist.get(0);
            nextbkid = Integer.parseInt(get_id_index);
            is_latest = nextbkid;
            } 
            
            else
            {
            if (nextbkid > is_latest) is_latest = nextbkid;
            }
            
        }
        bookingID = is_latest + 1;
        }
        else{
            bookingID = 1;
        }
    }
    

private boolean isInteger(String check){
        try
    {
        BigDecimal checkbd = new BigDecimal(check);
        return true;
    } catch (NumberFormatException ex)
    {
        return false;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Dos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbRoomCharges = new javax.swing.JLabel();
        lbServiceTax = new javax.swing.JLabel();
        lbTourismTax = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtpay = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtchange = new javax.swing.JTextField();
        btnpay = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Payment");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Days of stay:");

        Dos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Dos.setText("DOS");

        jLabel3.setText("Room charges:");

        jLabel4.setText("Service tax: ");

        jLabel5.setText("Tourism tax: ");

        jLabel6.setText("Total:");

        lbRoomCharges.setText("----------");

        lbServiceTax.setText("----------");

        lbTourismTax.setText("----------");

        lbTotal.setText("----------");

        jLabel7.setText("Pay (RM):");

        txtpay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpayFocusLost(evt);
            }
        });
        txtpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpayActionPerformed(evt);
            }
        });
        txtpay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpayKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpayKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpayKeyTyped(evt);
            }
        });

        jLabel8.setText("Change (RM):");

        txtchange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtchangeKeyTyped(evt);
            }
        });

        btnpay.setText("PAY");
        btnpay.setEnabled(false);
        btnpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpayActionPerformed(evt);
            }
        });

        btnback.setText("back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel9.setText("Press ENTER key to confirm pay amount.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnpay, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTotal)
                                    .addComponent(lbTourismTax)
                                    .addComponent(lbServiceTax)
                                    .addComponent(lbRoomCharges)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtchange, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Dos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Dos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbRoomCharges))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbServiceTax))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbTourismTax))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtchange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpay, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnback)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed

        this.dispose() ;       // TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpayActionPerformed
        String payamount = String.valueOf(pay);
        String changeamount = txtchange.getText();
        String roomfees = String.valueOf(roomcharges);
        String servicetaxs = String.valueOf(servicetax);
        String tourismtaxs = String.valueOf(tourismtax );
        String totalcharge = String.valueOf(totalfees); 
        String newbookingid = String.valueOf(bookingID);
        
        if (txtpay.getText().equals(payamount)){
        try{
            FileWriter fwbook = new FileWriter("booking.txt",true);
            BufferedWriter bwbook = new BufferedWriter(fwbook);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String start = sdf.format(startD);
            String end = sdf.format(endD);           
            
            bwbook.write(newbookingid);
            bwbook.newLine(); 
            bwbook.write(name);
            bwbook.newLine();            
            bwbook.write(email);
            bwbook.newLine();  
            bwbook.write(icnum);
            bwbook.newLine();  
            bwbook.write(number);
            bwbook.newLine();            
            bwbook.write(start);
            bwbook.newLine();  
            bwbook.write(end);
            bwbook.newLine();  
            bwbook.write(roomname);
            bwbook.newLine(); 
            bwbook.write("---");
            bwbook.newLine();  

            
            bwbook.close();
            
            FileWriter fwreceipt = new FileWriter("receipt.txt",true);
            BufferedWriter bwreceipt = new BufferedWriter(fwreceipt);
            bwreceipt.write(roomfees);
            bwreceipt.newLine();            
            bwreceipt.write(servicetaxs);
            bwreceipt.newLine();       
            bwreceipt.write(tourismtaxs);
            bwreceipt.newLine();   
            bwreceipt.write(totalcharge);
            bwreceipt.newLine();
            bwreceipt.write(payamount);
            bwreceipt.newLine();
            bwreceipt.write(changeamount);
            bwreceipt.newLine();
            bwreceipt.write(newbookingid);
            bwreceipt.newLine();
            bwreceipt.write("---");
            bwreceipt.newLine();
            
            bwreceipt.close();
            
           
             this.dispose();
            JOptionPane.showMessageDialog(null,"The booking has been successfully made"); 
             booking.setVisible(false);
            new Booking().setVisible(true);
        }  
           
        catch (IOException ex){
            JOptionPane.showMessageDialog(null,"Unable to create file due to " + ex);           
        }
        }
        else {JOptionPane.showMessageDialog(null,"Please make sure the pay amount is valid.");  }
    }//GEN-LAST:event_btnpayActionPerformed

    private void txtchangeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtchangeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtchangeKeyTyped

    private void txtpayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpayKeyTyped

        if (evt.getKeyChar() == KeyEvent.VK_ENTER){
        if (txtpay.getText().isEmpty() == false){
        if  (isInteger(txtpay.getText()) == true){
      BigDecimal temppay = new BigDecimal(txtpay.getText())  ;    
      pay = temppay;


      BigDecimal change = new BigDecimal(0);
      
      change = pay.subtract(totalfees);
      
      String changee = String.valueOf(change);
      BigDecimal change2 = new BigDecimal(changee);
      change2 = change2.setScale(2, BigDecimal.ROUND_HALF_EVEN);
      
      String changee2 = String.valueOf(change2);
      this.txtchange.setText(changee2);
      if(change.compareTo(BigDecimal.ZERO) > 0){
      this.btnpay.setEnabled(true); 
      }
             else {this.btnpay.setEnabled(false);}
     }   
             else {this.btnpay.setEnabled(false);}
     }
        
          }
          
    }//GEN-LAST:event_txtpayKeyTyped

    private void txtpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpayActionPerformed
  // TODO add your handling code here:
    }//GEN-LAST:event_txtpayActionPerformed

    private void txtpayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpayFocusLost
// TODO add your handling code here:
    }//GEN-LAST:event_txtpayFocusLost

    private void txtpayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpayKeyPressed
// TODO add your handling code here:
    }//GEN-LAST:event_txtpayKeyPressed

    private void txtpayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpayKeyReleased
    
    }//GEN-LAST:event_txtpayKeyReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dos;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnpay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbRoomCharges;
    private javax.swing.JLabel lbServiceTax;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTourismTax;
    private javax.swing.JTextField txtchange;
    private javax.swing.JTextField txtpay;
    // End of variables declaration//GEN-END:variables
}
